# fly.toml app configuration file generated for seedling-scheduler-angie on 2026-01-02T16:45:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'seedling-scheduler'
primary_region = 'ord'
console_command = '/rails/bin/rails console'

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = './bin/rails db:migrate'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    hard_limit = 1000
    soft_limit = 1000

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/up"

[[vm]]
  memory = '512mb'
  cpus = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpus = 1
  processes = ['worker']

[[mounts]]
  source = 'seedling_data'
  destination = '/rails/storage'
  initial_size = '1GB'

[env]
  RAILS_ENV = 'production'
  SOLID_QUEUE_IN_PUMA = 'true'
